### ISSUE TITLE
Fail upload files

### ISSUE THREAD

**Issue by Tocinofrito** [pawco/docker-lamp#1]
Trying to work with file upload, when i use `var_dump($_FILES['file']);` it show NULL, and trying to see some `ini_get`:
`echo 'file_uploads: ' . ini_get('file_uploads') . <br />';
echo 'upload_tmp_dir: ' . ini_get('upload_tmp_dir') . <br />';
echo 'upload_mac_filesize: ' . ini_get('upload_max_filesize') . <br />';
echo 'max_file_uploads: ' . ini_get('max_file_uploads') . <br />';`
shows
![error](https://user-images.githubusercontent.com/40874235/145499758-72ba4a58-a175-4217-a69d-e70e069b3d18.png)
:
HTML is correct

**Comment by pawco** [comment]
Thanks for reporting. As soon as I catch time I'll try to reproduce the issue.
